### ISSUE TITLE
Red Bike Slower

### ISSUE THREAD

**Issue by Andy5823** [G012188e/404-Name-Not-Found#11]
The red bike in 2 Player mode is slower than the blue bike.

Reproduction steps: 1) Start the game in 2 Player Mode. 2) The red bike will be slower >~50% of the time. 3) Turning as the red bike also slows it down.

Expected Result: Both bikes have the same speed.

Actual Result: Red is slower.

**Comment by G012188e** [comment]
Mix of delta time not used and the power-ups activating before they are in use
