### ISSUE TITLE
In consistent game speeds between player numbers and line breaks

### ISSUE THREAD

**Issue by Mike430** [G012188e/404-Name-Not-Found#17]
**DESCRIPTION:**
If you play a game with a different number of players than usual, you will get a game that runs at a different speed. If it's just two players, you'll get a slow game, if you play a game with 4, it is unmanageably fast. Also, lines appear to be drawn on a frame by frame basis, the faster the game is the more broken the line is

**HOW TO REPLICATE:**
Play a game with just two players, then a game with 3, then 4, you'll see the difference. 

**FREQUENCY OF OCCURRENCE:**
100%, this has happened every time I've tried it.

**SCREEN SHOTS:**
slow game but with smooth lines:
![bug 8](https://cloud.githubusercontent.com/assets/9351958/14764270/f3667d92-09a9-11e6-9dde-ceb4269341c7.png)

faster game and a more broken lines:
![bug 7](https://cloud.githubusercontent.com/assets/9351958/14764269/f36605b0-09a9-11e6-9265-b5a85cbc5fd3.png)

very fast game and no lines, only squares:
![bug 6](https://cloud.githubusercontent.com/assets/9351958/14764271/f36739b2-09a9-11e6-9cf4-fe60ca339dc0.png)

**DEVICE:**
Windows 10 PC. I played it both through cocos studio and visual studio, same results each time.

**Comment by rusty595** [comment]
This has been fixed but @G012188e has not yet pushed the his local copy with the changes to GitHub

**Comment by G012188e** [comment]
This happens on the computer but doesn't happen on the mobile devices
